/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Diet } from "./Diet";
import { DietCountArgs } from "./DietCountArgs";
import { DietFindManyArgs } from "./DietFindManyArgs";
import { DietFindUniqueArgs } from "./DietFindUniqueArgs";
import { CreateDietArgs } from "./CreateDietArgs";
import { UpdateDietArgs } from "./UpdateDietArgs";
import { DeleteDietArgs } from "./DeleteDietArgs";
import { DietService } from "../diet.service";
@graphql.Resolver(() => Diet)
export class DietResolverBase {
  constructor(protected readonly service: DietService) {}

  async _dietsMeta(
    @graphql.Args() args: DietCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Diet])
  async diets(@graphql.Args() args: DietFindManyArgs): Promise<Diet[]> {
    return this.service.diets(args);
  }

  @graphql.Query(() => Diet, { nullable: true })
  async diet(@graphql.Args() args: DietFindUniqueArgs): Promise<Diet | null> {
    const result = await this.service.diet(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Diet)
  async createDiet(@graphql.Args() args: CreateDietArgs): Promise<Diet> {
    return await this.service.createDiet({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Diet)
  async updateDiet(@graphql.Args() args: UpdateDietArgs): Promise<Diet | null> {
    try {
      return await this.service.updateDiet({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Diet)
  async deleteDiet(@graphql.Args() args: DeleteDietArgs): Promise<Diet | null> {
    try {
      return await this.service.deleteDiet(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
