/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { IngredientListRelationFilter } from "../../ingredient/base/IngredientListRelationFilter";
import { InventoryListRelationFilter } from "../../inventory/base/InventoryListRelationFilter";
import { MealListRelationFilter } from "../../meal/base/MealListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class DepartmentWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  departmentName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => IngredientListRelationFilter,
  })
  @ValidateNested()
  @Type(() => IngredientListRelationFilter)
  @IsOptional()
  @Field(() => IngredientListRelationFilter, {
    nullable: true,
  })
  ingredients?: IngredientListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => InventoryListRelationFilter,
  })
  @ValidateNested()
  @Type(() => InventoryListRelationFilter)
  @IsOptional()
  @Field(() => InventoryListRelationFilter, {
    nullable: true,
  })
  inventories?: InventoryListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => MealListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MealListRelationFilter)
  @IsOptional()
  @Field(() => MealListRelationFilter, {
    nullable: true,
  })
  meals?: MealListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  totalRequiredItems?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  totalRequiredMaterials?: IntNullableFilter;
}

export { DepartmentWhereInput as DepartmentWhereInput };
